# Generated by Django 2.2.5 on 2019-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190914_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='200', upload_to='item_images/%Y/%m/%d/', width_field='200'),
        ),
    ]
