# Generated by Django 2.2.5 on 2019-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='uploads')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(default='eTPibUX', editable=False, max_length=8)),
            ],
        ),
    ]
