# Generated by Django 2.2.5 on 2019-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifier',
            field=models.CharField(default='iBp5BRWD', editable=False, max_length=8),
        ),
    ]
