# Generated by Django 2.2.5 on 2019-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190914_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifier',
            field=models.CharField(default='h2LQPilj', editable=False, max_length=8),
        ),
    ]
