# Generated by Django 2.2.5 on 2019-09-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190914_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifier',
            field=models.CharField(default='', editable=False, max_length=8),
        ),
    ]
